push sc

diff --git a/.github/workflows/security-scan.yml b/.github/workflows/security-scan.yml
--- a/.github/workflows/security-scan.yml
+++ b/.github/workflows/security-scan.yml
@@ -1,18 +1,43 @@
 name: Security Scan
+
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 on:
-    push:
-        branches: [ main ]
-        paths-ignore: [ '.github/**', 'doc/**', 'docs/**', 'tools/**', 'catalog-info.yaml', 'README.md' ]
-    workflow_dispatch:
+  push:
+    branches:
+      - main
+      - test-checkmarx
+    paths-ignore: 
+      - '.github/**'
+      - 'doc/**'
+      - 'docs/**'
+      - 'tools/**'
+      - 'catalog-info.yaml'
+      - 'README.md'
+  pull_request:
+    branches:
+      - main
+      - test-checkmarx
 
 jobs:
-    security-scan:
+  security-scan:
+    runs-on: self-hosted
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Run Checkmarx scan
         uses: unzercorp/unzer-tech-toolbox/.github/workflows/security-scan.yaml@main
-        secrets:
-            CX_CLIENT_ID: ${{ secrets.CX_P3_CLIENT_ID }}
-            CX_CLIENT_SECRET: ${{ secrets.CX_P3_CLIENT_SECRET }}
-        additional_params:  --threshold "iac-high=5;iac-medium=10;sast-high=5;sast-medium=10;sca-high=10" --sast-filter '!tools/**,!docs/**,!**/src/test/**/*' --iac-security-filter '!tools/**,!docs/**,!**/src/test/**/*' --sca-filter '!tools/**,!docs/**,!**/src/test/**/*'
+        with:
+          CX_CLIENT_ID: ${{ secrets.CX_P3_CLIENT_ID }}
+          CX_CLIENT_SECRET: ${{ secrets.CX_P3_CLIENT_SECRET }}
+          additional_params: '--threshold "iac-high=5;iac-medium=10;sast-high=5;sast-medium=10;sca-high=10" --sast-filter'
+
+      - name: Check for policy violations
+        run: |
+          if grep -q "Policy Violation" "path/to/checkmarx/output"; then
+            echo "Checkmarx policy violation detected. Failing the build."
+            exit 1
+          fi
